include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 80

build-review:
  # These variables are available only for review env and are merged with the general variables defined above.
  extends: .build
  script:
    - echo "CI_PROJECT_DIR:"
    - echo $CI_PROJECT_DIR
    - ls -la $CI_PROJECT_DIR
    - echo "and where am I?"
    - pwd
    - ls -l
    - echo "CI_BUILDS_DIR:"
    - echo $CI_BUILDS_DIR
    - find $CI_BUILDS_DIR
    - cp $CI_PROJECT_DIR/.prod/robots.txt.review robots.txt
    - cat robots.txt
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.test.kuva.hel.ninja'
    DOCKER_BUILD_ARG_REACT_APP_API_URI: 'https://kukkuu.test.kuva.hel.ninja/graphql'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.test.kuva.hel.ninja'
    DOCKER_BUILD_ARG_REACT_APP_API_URI: 'https://kukkuu.test.kuva.hel.ninja/graphql'
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.test.kuva.hel.ninja'
    DOCKER_BUILD_ARG_REACT_APP_API_URI: 'https://kukkuu.test.kuva.hel.ninja/graphql'
  only:
    refs:
      - master

review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    POSTGRES_ENABLED: 0

# This will enable staging ci-pipeline
staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
  only:
    refs:
      - develop
