language: node_js
node_js:
  - '12'
cache:
  yarn: false
  directories:
    - node_modules
jobs:
  include:
    - stage: 'Test'
      name: 'Run code linting and test'
      script: yarn lint && yarn ci
    - stage: 'Build'
      name: 'Run (test) build'
      if: branch IN (master, develop)
      env:
        global:
          - NODE_ENV=production
      script: yarn build
after_success:
  - ./node_modules/.bin/codecov < coverage/lcov.info
