sudo: false
language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - yarn ci

build:
  script:
    - yarn build
  branches:
    only:
      - develop
      - master
      - feature/KK-31-ci-cd-config
