language: node_js
node_js:
  - '12'
jobs:
  include:
    - stage: 'Build'
      name: 'Run (test) build'
      if: branch IN (master, develop)
      script: NODE_ENV=production yarn && yarn build
after_success:
  - ./node_modules/.bin/codecov < coverage/lcov.info
