# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - '*release-please*'
      - '**/*.md'
      - '.github/'

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a
# merge commit, which is the merged code between the source and target branches
# of the pull request.
#
# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: kukkuu-pipelines
      type: git
      # Azure DevOps project/repository
      name: kukkuu/kukkuu-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-PROJECTNAME-api-release.yml
  # Drupal example: azure-pipelines-drupal-release.yml
  template: azure-pipelines-kukkuu-ui-test.yml@kukkuu-pipelines
  parameters:
    buildArgs:
      VITE_CMS_URI: 'https://kukkuu.app-staging.hkih.hion.dev/graphql'
      # TODO: Instead of using the Kukkuu API from the test environment, use a review specific API.
      # VITE_API_URI: 'https://kukkuu-local.api.dev.hel.ninja/graphql'
      VITE_API_URI: https://kukkuu.api.test.hel.ninja/graphql
      VITE_ADMIN_TICKET_VALIDATION_URL: 'https://kukkuu-admin.test.hel.ninja/check-ticket-validity'
      VITE_FEATURE_FLAG_SHOW_CORONAVIRUS_INFO: false
      BROWSER_TESTS_PROJECT_YEAR: 1234
    configMap: # pod environment variables
      BROWSER_TESTS_PROJECT_YEAR: 1234
  #imagetag: ${{ parameters.imagetag }}
